apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.vault.io/tls: "true"
    ingress.vault.io/ttl: "24h"
    ingress.vault.io/path: pki/issue/default
  name: vault
spec:
  rules:
  - host: vault.example.com
    http:
      paths:
      - backend:
          serviceName: vault
          servicePort: 8200
  tls:
  - hosts:
    - vault.example.com
    secretName: ingress-tls
